name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
        docker build -t ${{secrets.DOCKER_USERNAME}}/aleburrello --build-arg CURR_COMMIT=$GITHUB_SHA .
        docker push ${{secrets.DOCKER_USERNAME}}/aleburrello
      
  tests:

    runs-on: ubuntu-latest
    needs: [build]
    container:
        image: alessioburrello/aleburrello:latest
        volumes:
          - ${{ github.workspace }}:/dory_checkout
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run experiments
        run: |
          source /dory_env/bin/activate
          cd /gap_riscv_toolchain_ubuntu_18/gap_sdk
          source configs/gapuino_v3.sh
          cd /dory_checkout
          python3 -m pytest -x test_GAP8.py --compat "gap-sdk"
          echo $?
          source /pulp-sdk/configs/pulp-open-nn.sh
          export PULP_RISCV_GCC_TOOLCHAIN=/riscv-nn-toolchain/
          find . -path "*GAP8*HW_description.json" -exec sed -E -i 's/("name" *: *)"gap_sdk"/\1"pulp-sdk"/' {} +
          python3 -m pytest -x test_GAP8.py --compat "pulp-sdk"
          echo $?
        shell: bash
